[openai]
openai_api_key="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"

#Now we need a place to store these embeddings 
#and enable a efficient vector search through them all. 
#To do that we use Pinecone, we can get a free API key 
#and enter it below where we will initialize our connection 
#to Pinecone and create a new index.

# initialize connection to pinecone (get API key at app.pinecone.io)

# find your environment next to the api key in pinecone console